// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QKHawcf7OROB_KwIZCysCDqV00pQ8-g',
    appId: '1:902429078369:web:899a9d4ca5f59789cf4b20',
    messagingSenderId: '902429078369',
    projectId: 'goomy-technology',
    authDomain: 'goomy-technology.firebaseapp.com',
    storageBucket: 'goomy-technology.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsOpoubp-c7Tw2NE0GWcHF1WWvzhvf8OU',
    appId: '1:902429078369:android:5ecb0a8718536d03cf4b20',
    messagingSenderId: '902429078369',
    projectId: 'goomy-technology',
    storageBucket: 'goomy-technology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuoDczouyaDkfPQRJtOrXGFvB24m-XdvY',
    appId: '1:902429078369:ios:aac3e554660f0ad0cf4b20',
    messagingSenderId: '902429078369',
    projectId: 'goomy-technology',
    storageBucket: 'goomy-technology.appspot.com',
    iosClientId: '902429078369-qjhcf3t4m3k167o7cmnkhgcdt2edrjep.apps.googleusercontent.com',
    iosBundleId: 'tech.goomy.mediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuoDczouyaDkfPQRJtOrXGFvB24m-XdvY',
    appId: '1:902429078369:ios:aac3e554660f0ad0cf4b20',
    messagingSenderId: '902429078369',
    projectId: 'goomy-technology',
    storageBucket: 'goomy-technology.appspot.com',
    iosClientId: '902429078369-qjhcf3t4m3k167o7cmnkhgcdt2edrjep.apps.googleusercontent.com',
    iosBundleId: 'tech.goomy.mediaapp',
  );
}
